spring.application.name=backend
server.port=8080
server.servlet.context-path=/backend/api/v1

spring.datasource.url=jdbc:postgresql://localhost:5400/backend_db
spring.datasource.username=backend_user
spring.datasource.password=backend_password

spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.data.redis.database=0

spring.config.import=optional:file:.env[.properties]

# Ollama Cloud
app.ollama.cloud.base-url=https://ollama.com
app.ollama.cloud.api-key=${OLLAMA_API_KEY}
app.ollama.cloud.chat-model=gpt-oss:120b

# Ollama Local
app.ollama.local.base-url=http://localhost:11434
app.ollama.local.embedding-model=embeddinggemma:300m

spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.chat.memory.repository.jdbc.initialize-schema=always

logging.level.org.springframework.ai.chat.client.advisor=DEBUG
logging.level.org.springframework.ai=DEBUG